---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define dependency_packages.
  set_fact:
    dependency_packages: "{{ __dependency_packages | list }}"
  when: dependency_packages is not defined

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when:
    - not envoy_install_from_source
    - ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when:
    - not envoy_install_from_source
    - ansible_os_family == 'Debian'

# Install Envoy from source when envoy_install_from_source is true.
- include_tasks: install-from-source.yml
  when: envoy_install_from_source

# Configure Envoy.
#- include_tasks: configure.yml
